# Evaluating models

## Loading models

In [1]:
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model

c:\Users\foxin\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\foxin\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
c:\Users\foxin\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
c:\Users\foxin\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
v1 = load_model('modelV1.h5')
v2 = load_model('modelV2.h5')

In [3]:
from keras.utils import image_dataset_from_directory

In [14]:
testData = image_dataset_from_directory('augmented data/test', label_mode='categorical')

Found 4106 files belonging to 5 classes.


## Evaluating Model

In [15]:
from keras.metrics import Accuracy

In [17]:
v1_accuracy = Accuracy()

for i,batch in enumerate(testData):
    x, y = batch
    yhat = v1.predict(x)
    v1_accuracy.update_state(y, yhat)



1/1 [==============================] - 1s 610ms/step


In [18]:
v1_accuracy.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.056941062>

In [19]:
v2_accuracy = Accuracy()

for i,batch in enumerate(testData):
    x, y = batch
    yhat = v2.predict(x)
    v2_accuracy.update_state(y, yhat)

v2_accuracy.result()

1/1 [==============================] - 2s 2s/step


<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [21]:
v2_accuracy.result().numpy(), v1_accuracy.result()

(0.0, <tf.Tensor: shape=(), dtype=float32, numpy=0.056941062>)

In [22]:
from PIL import Image

In [42]:
testData.class_names

['bikes', 'cars', 'cycles', 'scooters', 'trucks']

In [43]:
def predict(image:str, model:keras.models.Model):
    img = tf.convert_to_tensor(Image.open(image).resize((256, 256)))
    prediction = model.predict(tf.expand_dims(img, 0), verbose=False)
    return testData.class_names[int(tf.argmax(prediction, 1).numpy())]

In [53]:
target = 'partitioned data/test/bikes/image.jpeg'
predV1 = predict(target, v1)
predV2 =  predict(target, v2)

predV1, predV2

('bikes', 'bikes')

For some reason v1 accuracy is 56% while v2 accuracy is 0%, but the v2 model is performing really well compared to v1